---
# tasks file for docker
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker and dependencies
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Reset connection to apply group changes
  meta: reset_connection