---
- hosts: localhost
  connection: local

  tasks:
    - name: Create EC2 instances if they don't exist
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "ahmad-aws-keypair"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
        state: present
      loop:
        - { image: "ami-0453ec754f44f9a4a", name: "manage-node-1" }
        - { image: "ami-0e2c8caa4b6378d8c", name: "manage-node-2" }
        - { image: "ami-0e2c8caa4b6378d8c", name: "manage-node-3" }

